# Generated by Django 3.2.7 on 2021-09-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='', max_length=60, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='', max_length=60, verbose_name='surname'),
        ),
    ]
