# Generated by Django 3.2.7 on 2021-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210909_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='surname'),
        ),
    ]
