# Generated by Django 3.2.7 on 2021-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210913_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='image',
            new_name='image_medium',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image_big',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
